### ISSUE TITLE
Make Consul Optional

### ISSUE THREAD

**Issue by Aaron-Ritter** [rogierslag/font-cacher#13]
Hi @rogierslag 

Really like the font-cacher 👍 :) i was wondering why my instances suddenly recycle permanently and found your latest commit [627bc3d](https://github.com/rogierslag/font-cacher/commit/627bc3d04055de48094a118aa3f118ef0c5ed3e5) 

It works without consul if you setup your own loadbalancer and I was wondering if it would be possible to make Consul optional e.g. disabling the use of consul with an ENV variable?

Aaron

**Comment by rogierslag** [comment]
Thanks for flagging this, that was surely unintentional! I've created a fix for this as version 2.0.0 (as it's a breaking change because registration is no longer attempted by default). The `latest` image on Docker hub now follows version 2.0.0 as well

**Comment by Aaron-Ritter** [comment]
perfect :) that works, thanks!
